### ISSUE TITLE
Add page for yourself to team directory

### ISSUE THREAD

**Issue by Ark20** [treehouse-apprenticeship/practice_project_athena#2]
* Add a new file to the `team` folder. Name the file with your first, and _, your last name and a `.md` extension. For example: `dave_mcfarland.md`
* Add your name and favorite food using this format
   ``` 
   # Dave McFarland
   *Favorite food:* Sushi 
   ```
See [this file](../blob/master/team/dave_mcfarland.md) as an example.

**Comment by mignonne87** [comment]
add page to team directory issue resolved.
